function guiCTD

% guiCTD
% N.Webster 6/19/25, based on initial code lines in compileCTD by 
% S.L.Danielson. GUI code based on Soundscape Metrics Remora GUI from Triton

global CTDstatic PARAMS

if isempty(PARAMS) == 1
    ctdstatic_settings_init
end

close all

defaultPos = [0.25,0.15,0.7,0.7];
CTDstatic.fig = figure; clf;

set(CTDstatic.fig,'NumberTitle','off', ...
    'Name','CTD Static Definitions',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on',...
    'ToolBar', 'none');

figure(CTDstatic.fig)

% Load/save settings pulldown:

CTDstatic.fig.Children = uimenu(CTDstatic.fig,'Label',...
        'Save/Load Settings','Enable','on','Visible','on');
    
    % load/save params:
    uimenu(CTDstatic.fig.Children,'Label','&Load Settings',...
        'Callback','ctdstatic_control(''ctdstatic_settingsLoad'')');
    uimenu(CTDstatic.fig.Children,'Label','&Save Settings',...
        'Callback','ctdstatic_control(''ctdstatic_settingsSave'')');
    

% Button grid layouts
% 12 rows, 2 columns
r = 30; % Rows (Extra space for separations between sections)
c = 6;  % Columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% Y Position (Rrelative Units)
y = 1:-h:0;

% X Position (Relative Units)
x = 0:w:1;

% Colors
bgColor = [1 1 1];  % White
bgColorRed = [1 .6 .6];  % Red
% bgColorGray = [.86 .86 .86];  % Gray
bgColor3 = [.75 .875 1]; % Light Green 
bgColor4 = [.76 .87 .78]; % Light Blue
bgColor5 = [.8672 0.6875 0.9570]; % Light Purple

CTDstatic.verify = [];

CTDstatic.params_help = ctdstatic_get_help_strings;

%% Title:

labelStr = 'CTD Project Settings';
btnPos=[x(1) y(2) c*w h];
CTDstatic.headtext = uicontrol(CTDstatic.fig, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',16,...
    'Visible','on');

%% Set paths and strings
%***********************************
% Input Directory Text
labelStr = 'Input Directory';
btnPos=[x(1) y(4)-ybuff w/2 h];
CTDstatic.verify.indirTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.indirHelp));
%  'BackgroundColor',bgColor3,...

% Input Directory Editable Text
%labelStr='C:\Users\nmwebster\Documents\projects\CTD';
labelStr = CTDstatic.indir;
btnPos=[x(1)+w/2 y(4) 2*w h];
CTDstatic.verify.indir = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','ctdstatic_control(''setindir'')');

% Change Input Directory Button
labelStr = 'Select';
btnPos=[x(1)+w*2.6 y(4) w/4 h];

CTDstatic.verify.indirSel = uicontrol(CTDstatic.fig,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor3,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.4,...
    'Visible','on',...
    'FontWeight','normal',...
    'Callback','ctdstatic_control(''indirSel'')');

%% Output Directory Text
labelStr = 'Output Directory';
btnPos=[x(1) y(5)-ybuff w/2 h];
CTDstatic.verify.outdirTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.outdirHelp));%   'BackgroundColor',bgColor3,...

% Output Folder Editable Text
%labelStr='C:\Users\nmwebster\Documents\projects\CTD';
labelStr=CTDstatic.outdir;
btnPos=[x(1)+w/2 y(5) 2*w h];
CTDstatic.verify.outdir = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setoutdir'')');

% Change Output Directory Button
labelStr = 'Select';
btnPos=[x(1)+w*2.6 y(5) w/4 h];

CTDstatic.verify.outdirSel = uicontrol(CTDstatic.fig,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor3,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.4,...
    'Visible','on',...
    'FontWeight','normal',...
    'Callback','ctdstatic_control(''outdirSel'')');

%% Output ASCII Filename Text
labelStr = 'Output ASCII Filename';
btnPos=[x(4) y(4)-ybuff w h];
CTDstatic.verify.outafnameTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.outafnameHelp));%   'BackgroundColor',bgColor3,...

% Output Filename Editable Text
%labelStr='ISC202506NPSOC.ascii';
labelStr=CTDstatic.outafname;
btnPos=[x(4)+w/1.2 y(4) 2*w h];
CTDstatic.verify.outafname = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setoutafname'')');

%% Output Header Filename Text
labelStr = 'Output Header Filename';
btnPos=[x(4) y(5)-ybuff w h];
CTDstatic.verify.outhfnameTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.outhfnameHelp));%   'BackgroundColor',bgColor3,...

% Output Filename Editable Text
%labelStr='ISC202506NPSOC.hdr';
labelStr=CTDstatic.outhfname;
btnPos=[x(4)+w/1.2 y(5) 2*w h];
CTDstatic.verify.outhfname = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setouthfname'')');

%% CTD Static Definitions Header
labelStr = 'CTD Static Definitions';
btnPos=[x(1) y(7) c*w h-ybuff];
CTDstatic.verify.ParamTxt = uicontrol(CTDstatic.fig, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorRed,...
    'String',labelStr, ...
    'FontWeight','bold',...    
    'FontSize',11,...
    'FontUnits','points',...
    'Visible','on');

%% Left column CTD Static Parameters

% Vessel
labelStr = 'Vessel';
btnPos=[x(1) y(9)-ybuff w/2 h];
CTDstatic.verify.vessTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.vessHelp));

% Vessel Editable Text
%labelStr = 'R/V Island C';
labelStr=CTDstatic.vess;
btnPos=[x(1)+w/2 y(9) w/1.5 h];
CTDstatic.verify.vess = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setvess'')');

%% Cruise
labelStr = 'Cruise';
btnPos=[x(1) y(10)-ybuff w/2 h];
CTDstatic.verify.cruiseTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.cruiseHelp));

% Cruise Editable Text
%labelStr = 'ISC202506NPSOC';
labelStr=CTDstatic.cruise;
btnPos=[x(1)+w/2 y(10) w/1.5 h];
CTDstatic.verify.cruise = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setcruise'')');

%% Project
labelStr = 'Project';
btnPos=[x(1) y(11)-ybuff w/2 h];
CTDstatic.verify.projectTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.projectHelp));

% Project Editable Text
%labelStr = 'NPS Outer Coast Pilot Study';
labelStr=CTDstatic.project;
btnPos=[x(1)+w/2 y(11) w/1.5 h];
CTDstatic.verify.project = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setproject'')');

%% Instrument
labelStr = 'Instrument';
btnPos=[x(2)+w/4 y(9)-ybuff w/2 h];
CTDstatic.verify.instrumentTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.instrumentHelp));

% Instrument Editable Text
%labelStr = 'SBE9';
labelStr=CTDstatic.instrument;
btnPos=[x(2)+w*0.75 y(9) w/1.5 h];
CTDstatic.verify.instrument = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setinstrument'')');

%% PI
labelStr = 'PI';
btnPos=[x(2)+w/4 y(10)-ybuff w/2 h];
CTDstatic.verify.piTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.piHelp));

% PI Editable Text
%labelStr = 'Danielson';
labelStr=CTDstatic.pi;
btnPos=[x(2)+w*0.75 y(10) w/1.5 h];
CTDstatic.verify.pi = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setpi'')');

%% Right Column CTD Static Parameters
% Agency text
labelStr = 'Agency';
btnPos=[x(3)+w/2 y(9)-ybuff w/2 h];
CTDstatic.verify.agencyTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.agencyHelp));

% Agency Editable Text
%labelStr = 'NPS';
labelStr=CTDstatic.agency;
btnPos=[x(3)+w y(9) w/1.5 h];
CTDstatic.verify.agency = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setagency'')');

%% Region
labelStr = 'Region';
btnPos=[x(3)+w/2 y(10)-ybuff w/2 h];
CTDstatic.verify.regionTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.regionHelp));

% Region Editable Text
%labelStr = 'Gulf of Alaska';
labelStr=CTDstatic.region;
btnPos=[x(3)+w y(10) w/1.5 h];
CTDstatic.verify.region = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setregion'')');

%% Data restrictions
labelStr = 'Data Restrictions';
btnPos=[x(3)+w/2 y(11)-ybuff w/2 h];
CTDstatic.verify.dataresTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.dataresHelp));

% Data restrictions Editable Text
%labelStr='n';
labelStr=CTDstatic.datares;
btnPos=[x(3)+w y(11) w/1.5 h];
CTDstatic.verify.datares = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setdatares'')');

%% Time offset
labelStr = 'Time Offset';
btnPos=[x(4)+w*0.75 y(9)-ybuff w/2 h];
CTDstatic.verify.timeoffTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.timeoffHelp));

% Time offset Editable Text
%labelStr='0/24';
labelStr=CTDstatic.timeoff;
btnPos=[x(4)+w*1.25 y(9) w/1.5 h];
CTDstatic.verify.timeoff = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''settimeoff'')');

%% Year
labelStr = 'Year';
btnPos=[x(4)+w*0.75 y(10)-ybuff w/2 h];
CTDstatic.verify.timeTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(CTDstatic.params_help.yearHelp));

% Year Editable Text
%labelStr='2025';
labelStr=CTDstatic.year;
btnPos=[x(4)+w*1.25 y(10) w/1.5 h];
CTDstatic.verify.year = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setyear'')');

%% Processing Options Header
labelStr = 'CTD Processing & Plotting Options';
btnPos=[x(1) y(13) c*w h-ybuff];
CTDstatic.verify.ParamTxt = uicontrol(CTDstatic.fig, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorRed,...
    'String',labelStr, ...
    'FontWeight','bold',...    
    'FontSize',11,...
    'FontUnits','points',...
    'Visible','on');

%% Upcast Downcast Option
% UpcastDowncast Checkbox
btnPos=[x(1)+w*0.1 y(15) w/1.5 h];
CTDstatic.verify.updown = uicontrol(CTDstatic.fig,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setupdown'')');

    if ~isempty(CTDstatic.updown)
        CTDstatic.verify.updown.Value = CTDstatic.updown;
    end

% text
labelStr = 'Manual Selection of Upcast or Downcast';
btnPos=[x(1)+w*0.2 y(15) w/2 h];
CTDstatic.verify.updownTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(CTDstatic.params_help.updownHelp));

%% CTD Interpolate Option
% Interpolate Checkbox
btnPos=[x(1)+w*0.1 y(16) w/1.5 h];
CTDstatic.verify.interp = uicontrol(CTDstatic.fig,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setinterp'')');

    if ~isempty(CTDstatic.interp)
        CTDstatic.verify.interp.Value = CTDstatic.interp;
    end

% text
labelStr = 'Data Interpolation';
btnPos=[x(1)+w*0.2 y(16)-ybuff w/2 h];
CTDstatic.verify.interpTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'BackgroundColor', bgColor4,...
   'FontWeight','bold',...
   'TooltipString',sprintf(CTDstatic.params_help.interpHelp));

% Save data options that are only available if data interpolation is
% checked (SaveD.m script)
    
    btnPos=[x(2) y(22) w*1.2 h*8];
    CTDstatic.verify.interpOp = uipanel(CTDstatic.fig,...
        'Title','Interpolation Options',...
        'Position',btnPos,...
        'BackgroundColor', bgColor4,...
        'FontWeight','bold',...
        'Visible','on');
    labelStr = CTDstatic.params_help.interpOpHelp;
    btnPos=[x(2)+w*0.05 y(16)+ybuff w*1.1 h];
    CTDstatic.verify.interpOpTxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'BackgroundColor', bgColor4,...
       'FontAngle','italic');

    
    % dupe CNV option
    btnPos=[x(2)+w*0.1 y(17) w/1.5 h];
    CTDstatic.verify.dupeCNV = uicontrol(CTDstatic.fig,...
        'Style','checkbox',...
        'Units','normalized',...
        'Position',btnPos,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'BackgroundColor',bgColor4,...
        'Callback','ctdstatic_control(''setdupeCNV'')');
    
        if ~isempty(CTDstatic.dupeCNV)
            CTDstatic.verify.dupeCNV.Value = CTDstatic.dupeCNV;
        end

    % dupe CNV text
    labelStr = 'Create Interpolated Cast CNVs';
    btnPos=[x(2)+w*0.2 y(17)-ybuff w*0.9 h];
    CTDstatic.verify.dupeCNVTxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'BackgroundColor',bgColor4,...
       'TooltipString',sprintf(CTDstatic.params_help.dupeCNVHelp));

    % add NMEA option
    btnPos=[x(2)+w*0.1 y(18) w/1.5 h];
    CTDstatic.verify.addNMEA = uicontrol(CTDstatic.fig,...
        'Style','checkbox',...
        'Units','normalized',...
        'Position',btnPos,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'BackgroundColor',bgColor4,...
        'Callback','ctdstatic_control(''setaddNMEA'')');
    
        if ~isempty(CTDstatic.addNMEA)
            CTDstatic.verify.addNMEA.Value = CTDstatic.addNMEA;
        end

    % add NMEA text
    labelStr = 'Add NMEA Data Column from Header';
    btnPos=[x(2)+w*0.2 y(18)-ybuff w*0.9 h];
    CTDstatic.verify.addNMEATxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'BackgroundColor',bgColor4,...
       'TooltipString',sprintf(CTDstatic.params_help.addNMEAHelp));

    % Fix bottom depth string option
    btnPos=[x(2)+w*0.1 y(19) w/1.5 h];
    CTDstatic.verify.botDep = uicontrol(CTDstatic.fig,...
        'Style','checkbox',...
        'Units','normalized',...
        'Position',btnPos,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'BackgroundColor',bgColor4,...
        'Callback','ctdstatic_control(''setbotDep'')');
    
        if ~isempty(CTDstatic.botDep)
            CTDstatic.verify.botDep.Value = CTDstatic.botDep;
        end

    % Fix bottom depth text
    labelStr = 'Fix Bottom Depth Header String';
    btnPos=[x(2)+w*0.2 y(19)-ybuff w*0.9 h];
    CTDstatic.verify.botDepTxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'BackgroundColor',bgColor4,...
       'TooltipString',sprintf(CTDstatic.params_help.botDepHelp));

    %Bottom Depth String
    labelStr = 'Bottom Depth String';
    btnPos=[x(2)+w*0.005 y(20)-ybuff w/1.5 h];
    CTDstatic.verify.botForTxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'BackgroundColor',bgColor4,...
       'TooltipString',sprintf(CTDstatic.params_help.botForHelp));
    
    % Bottom Depth String Editable Text
    labelStr=CTDstatic.botFor;
    btnPos=[x(2)+w*0.1 y(21) w*0.9 h];
    CTDstatic.verify.botFor = uicontrol(CTDstatic.fig,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','ctdstatic_control(''setbotFor'')');


%% Extrapolate Option
% Extrapolate Checkbox
btnPos=[x(1)+w*0.1 y(17) w/1.5 h];
CTDstatic.verify.extrap = uicontrol(CTDstatic.fig,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setextrap'')');

    if ~isempty(CTDstatic.extrap)
        CTDstatic.verify.extrap.Value = CTDstatic.extrap;
    end

% text
labelStr = 'Extrapolate Across Missing Bins';
btnPos=[x(1)+w*0.2 y(17) w/2 h];
CTDstatic.verify.extrapTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(CTDstatic.params_help.extrapHelp));

%% Print EPS Option
% EPS Checkbox
btnPos=[x(1)+w*0.1 y(18) w/1.5 h];
CTDstatic.verify.eps = uicontrol(CTDstatic.fig,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''seteps'')');

    if ~isempty(CTDstatic.eps)
        CTDstatic.verify.eps.Value = CTDstatic.eps;
    end

% text
labelStr = 'Print EPS';
btnPos=[x(1)+w*0.2 y(18)-ybuff w/2 h];
CTDstatic.verify.epsTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(CTDstatic.params_help.epsHelp));

%% Print PNG Option
% PNG Checkbox
btnPos=[x(1)+w*0.1 y(19) w/1.5 h];
CTDstatic.verify.png = uicontrol(CTDstatic.fig,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setpng'')');

    if ~isempty(CTDstatic.png)
        CTDstatic.verify.png.Value = CTDstatic.png;
    end

% text
labelStr = 'Print PNG';
btnPos=[x(1)+w*0.2 y(19)-ybuff w/2 h];
CTDstatic.verify.pngTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(CTDstatic.params_help.pngHelp));

%% Compile Bottles Option
% Compile Bottles Checkbox
btnPos=[x(1)+w*0.1 y(20) w/1.5 h];
CTDstatic.verify.compbot = uicontrol(CTDstatic.fig,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setcompbot'')');

    if ~isempty(CTDstatic.compbot)
        CTDstatic.verify.compbot.Value = CTDstatic.compbot;
    end

% text
labelStr = 'Compile Bottles';
btnPos=[x(1)+w*0.2 y(20)-ybuff w/2 h];
CTDstatic.verify.compbotTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(CTDstatic.params_help.compbotHelp));

%% Compile CNV Option
% Compile CNV Checkbox
btnPos=[x(1)+w*0.1 y(21) w/1.5 h];
CTDstatic.verify.compcnv = uicontrol(CTDstatic.fig,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setcompcnv'')');

    if ~isempty(CTDstatic.compcnv)
        CTDstatic.verify.compcnv.Value = CTDstatic.compcnv;
    end

% text
labelStr = 'Compile CNVs';
btnPos=[x(1)+w*0.2 y(21)-ybuff w/2 h];
CTDstatic.verify.compcnvTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(CTDstatic.params_help.compcnvHelp));

%% Plot SELECT Sensors Option
% Plot select sensors Checkbox
btnPos=[x(1)+w*0.1 y(22) w/1.5 h];
CTDstatic.verify.pltsel = uicontrol(CTDstatic.fig,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setpltsel'')');

    if ~isempty(CTDstatic.pltsel)
        CTDstatic.verify.pltsel.Value = CTDstatic.pltsel;
    end

% text
labelStr = 'Plot SELECT Sensors';
btnPos=[x(1)+w*0.2 y(22)-ybuff w/1.5 h];
CTDstatic.verify.pltselTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'BackgroundColor',bgColor5,...
   'FontWeight','bold',...
   'TooltipString',sprintf(CTDstatic.params_help.pltselHelp));

    btnPos=[x(4)+w*0.8 y(25) w*2 h*11];
    CTDstatic.verify.pltOp = uipanel(CTDstatic.fig,...
        'Title','Plotting Options',...
        'Position',btnPos,...
        'BackgroundColor', bgColor5,...
        'FontWeight','bold',...
        'Visible','on');
    labelStr = CTDstatic.params_help.pltOpHelp;
    btnPos=[x(4)+w*0.85 y(16)+ybuff w*1.8 h];
    CTDstatic.verify.pltOpTxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'BackgroundColor', bgColor5,...
       'FontAngle','italic');
    
    % Primary CTD Variables
    labelStr = 'Primary CTD Variables';
    btnPos=[x(4)+w*1.3 y(17) w*1.1 h];
    CTDstatic.verify.pltOpTxt2 = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'FontWeight','bold',...
       'BackgroundColor', bgColor5);

    % Rows String
    labelStr = '# Rows';
    btnPos=[x(4)+w*0.9 y(18)-ybuff w/1.5 h];
    CTDstatic.verify.rowsTxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'BackgroundColor',bgColor5);

    % Rows Editable Text
    labelStr=CTDstatic.nROW;
    btnPos=[x(4)+w*1.4 y(18) w*0.4 h];
    CTDstatic.verify.nROW = uicontrol(CTDstatic.fig,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','ctdstatic_control(''setnROW'')');

    % Columns String
    labelStr = '# Columns';
    btnPos=[x(4)+w*0.9 y(19)-ybuff w/1.5 h];
    CTDstatic.verify.rowsTxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'BackgroundColor',bgColor5);

    % Columns Editable Text
    labelStr=CTDstatic.nCOL;
    btnPos=[x(4)+w*1.4 y(19) w*0.4 h];
    CTDstatic.verify.nCOL = uicontrol(CTDstatic.fig,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','ctdstatic_control(''setnCOL'')');

    % Max Pressure String
    labelStr = 'Max Pressure';
    btnPos=[x(4)+w*0.9 y(20)-ybuff w/1.5 h];
    CTDstatic.verify.rowsTxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'BackgroundColor',bgColor5);

    % Max Pressure Editable Text
    labelStr=CTDstatic.maxPRESSURE;
    btnPos=[x(4)+w*1.4 y(20) w*0.4 h];
    CTDstatic.verify.maxPRESSURE = uicontrol(CTDstatic.fig,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','ctdstatic_control(''setmaxPRESSURE'')');

    % Select Sensors
    labelStr = 'Select Sensors';
    btnPos=[x(5)+w*1.1 y(17) w*0.6 h];
    CTDstatic.verify.pltOpTxt3 = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'FontWeight','bold',...
       'BackgroundColor', bgColor5);

    % SS Rows Editable Text
    labelStr=CTDstatic.nROW_SS;
    btnPos=[x(5)+w*1.1 y(18) w*0.4 h];
    CTDstatic.verify.nROW_SS = uicontrol(CTDstatic.fig,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','ctdstatic_control(''setnROW_SS'')');

    % SS Columns Editable Text
    labelStr=CTDstatic.nCOL_SS;
    btnPos=[x(5)+w*1.1 y(19) w*0.4 h];
    CTDstatic.verify.nCOL_SS = uicontrol(CTDstatic.fig,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','ctdstatic_control(''setnCOL_SS'')');

    % SS Max Pressure Editable Text
    labelStr=CTDstatic.maxPRESSURE_SS;
    btnPos=[x(5)+w*1.1 y(20) w*0.4 h];
    CTDstatic.verify.maxPRESSURE_SS = uicontrol(CTDstatic.fig,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','ctdstatic_control(''setmaxPRESSURE_SS'')');

    % Select Sensors Variables String
    labelStr = 'Select Sensors Variables';
    btnPos=[x(4)+w*0.9 y(22) w/1.8 h];
    CTDstatic.verify.rowsTxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'FontWeight','bold',...
       'BackgroundColor',bgColor5);
    
    % Plot select sensors choices pop up menu
    btnPos=[x(4)+w*1.4 y(23)-ybuff 1.1*w 2*h];
    labelStr = {'PROPERTIES (Temperature, Salinity, Density, Fluorescence, PAR/Irradiance, Altimeter)','RAW VOLTATGES (v0-v7)'};
    CTDstatic.verify.SSsel = uicontrol(CTDstatic.fig,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr, ...
    'Visible','on',...
    'Max',1,...
    'Callback','ctdstatic_control(''setSSsel'')');
    
    if ~isempty(CTDstatic.SSsel)
        CTDstatic.verify.SSsel.Value = CTDstatic.SSsel;
    end

    % Select Sensors UP DOWN
    labelStr = 'Select Sensors Data to Plot';
    btnPos=[x(4)+w*0.9 y(24) w/1.2 h];
    CTDstatic.verify.sspltTxt = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'FontWeight','bold',...
       'BackgroundColor',bgColor5);
    labelStr = '(1 = Downcast, 0 = Upcast)';
    btnPos=[x(4)+w*0.9 y(24)-3*ybuff w/1.2 h];
    CTDstatic.verify.sspltTxt2 = uicontrol(CTDstatic.fig,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'HorizontalAlignment','left',...
       'FontWeight','normal',...
       'BackgroundColor',bgColor5,...
       'TooltipString',sprintf(CTDstatic.params_help.sspltHelp));

    % Select Sensors UP DOWN Editable Text
    labelStr=CTDstatic.UPdown_SS;
    btnPos=[x(5)+w/1.4 y(25)+3*ybuff w/2 h*1.5];
    CTDstatic.verify.UPdown_SS = uicontrol(CTDstatic.fig,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','ctdstatic_control(''setUPdown_SS'')');

%% Depth Latitude
labelStr = 'Latitude for Depth Calculation';
btnPos=[x(3)+w/2 y(16)+3*ybuff w/2 h];
CTDstatic.verify.depLatTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(CTDstatic.params_help.depLatHelp));

% Depth Latitude Editable Text
labelStr=CTDstatic.depLat;
btnPos=[x(3)+w y(16) w/2 h*2];
CTDstatic.verify.depLat = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setdepLat'')');

%% Data to Plot Options
labelStr = 'Data to Plot';
btnPos=[x(3)+w/2 y(17)-ybuff w/2 h];
CTDstatic.verify.pltTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(CTDstatic.params_help.pltHelp));

labelStr = '(1 = Downcast, 0 = Upcast, 2 = Both)';
btnPos=[x(3)+w/2 y(18)+ybuff w/2 h];
CTDstatic.verify.pltTxt2 = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(CTDstatic.params_help.pltHelp));

%Data to plot Editable Text
labelStr=CTDstatic.pltDat;
btnPos=[x(3)+w y(18) w/2 h*2];
CTDstatic.verify.pltDat = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setpltDat'')');

%% Exclude Data Columns Option
labelStr = 'Data Columns to Exclude';
btnPos=[x(3)+w/2 y(20)+3*ybuff w/2 h];
CTDstatic.verify.excluTxt = uicontrol(CTDstatic.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(CTDstatic.params_help.excluHelp));

% Exclude Data Columns Editable Text
labelStr=CTDstatic.excluDat;
btnPos=[x(3)+w y(20) w/2 h*2];
CTDstatic.verify.excluDat = uicontrol(CTDstatic.fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ctdstatic_control(''setexcluDat'')');

%% Run Button
labelStr = 'Begin Level 2 CTD Data Processing';
btnPos=[x(3) y(30) w*2 h];

CTDstatic.verify.runTxt = uicontrol(CTDstatic.fig,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor3,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','ctdstatic_control(''rundata'')');
1;
